# configuration for creating a GIF out from com4FlowPy's results videoData

[GENERAL]
# release id for that the video is created (only one is possible)
relId =
# simulation hash id of the simulation for that
simhash =
# provide the variable that should be plotted (it needs to exist in the videoData folder)
# possible options:
#                    z_delta
#                    flux
#                    min_distance           (max travel length)
#                    max_gamma              (max travelAngle)variable = z_delta
#                    velocity               (computed from zDelta)
videoDataVariable = velocity
# choose if the thalweg defined as center of energy (coE) or center of flux (coF) is plotted
centerOf = coF
# frames per second of the output video (playback speed)
fps = 5
# number of generation steps merged into a single video frame
gensPerFrame = 3
# colormap for the raster data
cmap = viridis

# color, linewidth, point size and transparency for the thalweg data
thalwegColor = red
thalwegWidth = 2

pointColor = red
pointSize = 8

outlineColor = white
outlineWidth = 1.

historyAlpha = 0.5
currentAlpha = 0.95

historyPointsColor = k
historyPointsAlpha = 0.3
historyPointsSize = 7

# if True, the last frame shows the extended (and resampled) path (that is read from the pickle file)
showExtendedPath = True
# the duraion of the last frame if the extended path is shown
finalFrameDurationMs = 5000

[HILLSHADE]
azimuth = 315
altitude = 45
vertExag = 1.0

[PATH]
# if paths are empty the files are expected in the Avaframe structure
demPath =
videoDataPath =
outVideoPath =
extendedProfilePicklePath =