[GENERAL]

simHash = b29b7b1962

modName = com4FlowPy

# column and row number (x and y  coordinate of raster) of the starting cell of the thalweg/path
startRow = 469
startCol = 219

# output variable that is plotted (of whole simulation)
plotVariable = zDelta
# which center of is used (possible:'CoE' (default), 'CoZd', 'CoF')
centerOfVariable = CoE

thalwegPra=False