[GENERAL]

# The simulation hash of the simulation that is analysed
simHash = b29b7b1962

# Module name of the simulation that is analysed (the analysis is tested for com4FlowPy)
modName = com4FlowPy

# column and row number (x and y  coordinate of raster) of the starting cell of the thalweg/path
startRow = 469
startCol = 219

# output variable that is plotted (of whole simulation)
plotVariable = zdelta
# which center of is used
# possible:CoE (default), CoZd, CoF)
centerOfVariable = CoE

# If True, all thalwegs are represented in the field plot (upper panel)
thalwegPra=False