[GENERAL]

# The simulation hash of the simulation that is analysed
simHash = b29b7b1962

# Module name of the simulation that is analysed (the analysis is tested for com4FlowPy)
modName = com4FlowPy

# column and row number (x and y  coordinate of raster) of the starting cell of the thalweg/path
# if startRow or startCol is empty, for all thalwegData (with relating center of variable) are plotted
startRow =
startCol =

# output variable that is plotted (of whole simulation)
plotVariable = zdelta
# which center of is used
# possible:CoF (center of flux, default), CoZd (center of zdelta), CoE(center of energy)
# if empty all files are plotted
centerOfVariable = CoF

# If True, all thalwegs are represented in the field plot (upper panel)
thalwegPra = True

# Avalanche size is only for the plot title
avalancheSize =