### Config File - This file contains the main settings for the rock avalanche simulation run
## Copy to  local_com6RockAvalancheCfg.ini and set your parameters


[GENERAL]


[com1DFA_com1DFA_override]

#####
# PLEASE NOTE: these settings are untested and highly experimental. Use with caution!
#####

# use default com1DFA config as base configuration (True) and override following parameters
# if False and local_com1DFACfg is available use local
defaultConfig = True

#+++++++++++++ Output++++++++++++
# desired result Parameters (ppr, pft, pfv, pta, FT, FV, P, FM, Vx, Vy, Vz, TA, particles) - separated by |
resType = pft|pfv|ppr|FT

#+++++++++SNOW properties
# density of snow [kg/m³]
rho = 2500

#+++++++++++++SPH parameters
# SPH gradient option
# 0) No pressure gradients computed
# 1) SamosAT style (no reprojection on the surface, dz = 0 and gz is used)
# 2) SamosAT done in the cartesian coord system (reprojection on the surface, dz != 0 and g3 is used)
# 3) SamosAT but done in the local coord system (will hopefully allow us to add the earth pressure coef)
# and this time reprojection on the surface, dz not 0 and g3 is used
sphOption = 3

#++++++++++++++++ Particles
# mass per particle (if MPPDIR is used) [kg]
massPerPart = 280000.
# release thickness per particle (if MPPDH is used) [m]
deltaTh = 1.0
# splitting option
# either split particles based on mass (splitOption = 0)
# or split/merge in order to keep a constant number of particles per kernel radius(splitOption = 1)
splitOption = 1

#++++++++++++Friction model
# Please note that each type has their own/separate parameters!
frictModel = Voellmy
#+++++++++++++Voellmy friction model
muvoellmy = 0.035
xsivoellmy = 700.
# expected mesh size [m]
meshCellSize = 5

# density of entrained snow [kg/m³]
rhoEnt = 100
#+++++Entrainment thickness++++
# True if entrainment thickness should be read from file (shapefile, raster); if False - entTh read from ini file (only available for shapefile)
entThFromFile = True
# if a thickness value is missing for the entrainment feature in the provided shp file this value is used for all features [m]
entThIfMissingInShp = 0.3
# VARIATION options only if ENT file is a shapefile --------
# if a variation on entTh shall be performed add here +- percent and number of steps separated by $
# for example entThPercentVariation=50$10 [%]
entThPercentVariation =
# if a variation on entTh shall be performed add here +- absolute value and number of steps separated by $
# for example entThRangeVariation=0.5$10 [m]
entThRangeVariation =
# if a variation on entTh shall be performed add here +- ci% value and number of steps separated by $
# for example entThRangeFromCiVariation= ci95$10
entThRangeFromCiVariation =
# if variation on entTh shall be performed using a normal distribution in number of steps,
# value of buildType (ci95 value), min and max of dist in percent, buildType (ci95 only allowed),
# support (e.g. 10000) all separated by $: e.g. normaldistribution$numberOfSteps$0.3$95$ci95$10000
# if entFromShp=True ci95 is read from shp file too
entThDistVariation =
# entrainment thickness (only considered if ENT file is shapefile and entThFromFile=False) [m]
entTh =


#++++++++++++ Entrainment Erosion Energy
# Used to determine speed loss via energy loss due to entrained mass
entEroEnergy = 5000
entShearResistance = 0
entDefResistance = 0

#++++++++++++ Resistance model
# default setup:
ResistanceModel = default
# At each time step, ResistanceModel default applies increased friction and optional detrainment (see below). Only relevant in resistance areas.
# NOTE: development setup; parameter values need more testing and calibration!!

#  parameter for increased friction in resistance areas
cResH = 0.01

# Apply detrainment in resistance areas in accordance with the flow thickness and flow velocity thresholds specified below.
# if False - only increased friction is applied in resistance areas
detrainment = True

# detrainment parameter defined by Feistl et al. (2014)
detK = 5

# thresholds if detrainment is set to True
# FV OR FT below min thresholds: apply only detrainment. no increased friction
# FV AND FT within min and max thresholds: no detrainment, only apply increased friction
# FV OR FT above max thresholds: no detrainment and no increased friction applied
forestVMin = 6.
forestThMin = 0.6
forestVMax = 40.
forestThMax = 10.


