### Config File - This file contains the main settings for the simulation run
## Copy to  local_com1DFACfg.ini and set you parameters
# This file is part of Avaframe.


[GENERAL]
#+++++++++++++general start conditions: time dependent release
# if timeDependentRelease is True, provide the the timesteps, thickness and velocity
# for a releases in a csv-file in the REL folder
timeDependentRelease = True


[INPUT]
# specify a particular release area scenario, provide name of shapefile with or without extension .shp (optional)
releaseScenario = release1PF
